#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


def safe_div(num: float, den: float) -> float:
    if den == 0 or math.isnan(num) or math.isnan(den):
        return float("nan")
    return num / den


@dataclass(frozen=True)
class Point:
    l1_kb: int
    ipc: float


def read_ipc_series(csv_path: Path, app: str) -> List[Point]:
    points: List[Point] = []
    with csv_path.open(newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            if row.get("app") != app:
                continue
            if row.get("complete") not in ("1", "True", "true"):
                continue
            l1_kb = int(float(row["l1_kb"]))
            ipc = float(row["ipc"]) if row.get("ipc") else float("nan")
            points.append(Point(l1_kb=l1_kb, ipc=ipc))
    points.sort(key=lambda p: p.l1_kb)
    return points


def plot_two_series(
    a_x: List[int],
    a_y: List[float],
    a_label: str,
    b_x: List[int],
    b_y: List[float],
    b_label: str,
    title: str,
    ylabel: str,
    outpath: Path,
) -> None:
    plt.figure(figsize=(6.2, 3.6))
    plt.plot(a_x, a_y, marker="o", label=a_label)
    plt.plot(b_x, b_y, marker="o", label=b_label)
    plt.grid(True, alpha=0.25)
    plt.title(title)
    plt.xlabel("Tamanho L1 (KB)")
    plt.ylabel(ylabel)
    plt.legend()
    plt.tight_layout()
    outpath.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(outpath, dpi=200)
    plt.close()


def best_point(points: List[Point], power_mw: float) -> Tuple[int, float]:
    best_l1 = -1
    best_eff = float("nan")
    for p in points:
        eff = safe_div(p.ipc, power_mw)
        if math.isnan(eff):
            continue
        if best_l1 < 0 or eff > best_eff:
            best_l1 = p.l1_kb
            best_eff = eff
    return best_l1, best_eff


def main() -> None:
    ap = argparse.ArgumentParser(description="Q11 - energy efficiency (IPC / mW) vs L1")
    ap.add_argument(
        "--a7-csv",
        default="/home/xfalc/arq/TP4_EX4/analysis/q4_a7_results.csv",
        help="CSV produced by q4_collect_a7.py",
    )
    ap.add_argument(
        "--a15-csv",
        default="/home/xfalc/arq/TP4_EX4/analysis/q5_a15_results.csv",
        help="CSV produced by q5_collect_a15.py",
    )
    ap.add_argument(
        "--fig-base",
        default="/home/xfalc/arq/TP4_EX4/tex/figs/q11",
        help="Directory to write figures",
    )
    ap.add_argument(
        "--out-table-tex",
        default="/home/xfalc/arq/TP4_EX4/tex/tables/q11_energy_summary.tex",
        help="LaTeX table output path",
    )
    args = ap.parse_args()

    a7_csv = Path(args.a7_csv)
    a15_csv = Path(args.a15_csv)
    fig_base = Path(args.fig_base)
    out_table_tex = Path(args.out_table_tex)

    # From Q10 at f_max.
    p_a7_mw = 100.0
    p_a15_mw = 500.0

    apps = [
        ("dijkstra", "Dijkstra"),
        ("blowfish_total", "Blowfish (enc+dec)"),
    ]

    rows: List[Dict[str, str]] = []

    for app_key, app_label in apps:
        a7_pts = read_ipc_series(a7_csv, app_key)
        a15_pts = read_ipc_series(a15_csv, app_key)

        a7_x = [p.l1_kb for p in a7_pts]
        a15_x = [p.l1_kb for p in a15_pts]
        a7_y = [safe_div(p.ipc, p_a7_mw) for p in a7_pts]
        a15_y = [safe_div(p.ipc, p_a15_mw) for p in a15_pts]

        plot_two_series(
            a7_x,
            a7_y,
            "Cortex A7 (P=100mW)",
            a15_x,
            a15_y,
            "Cortex A15 (P=500mW)",
            f"Q11 - Efficacité énergétique (IPC/mW) vs L1 - {app_label}",
            "IPC / mW",
            fig_base / f"q11_energy_{app_key}.png",
        )

        best_a7_l1, best_a7_eff = best_point(a7_pts, p_a7_mw)
        best_a15_l1, best_a15_eff = best_point(a15_pts, p_a15_mw)
        rows.append(
            {
                "app": app_label,
                "best_a7_l1_kb": str(best_a7_l1),
                "best_a7_eff": f"{best_a7_eff:.6f}",
                "best_a15_l1_kb": str(best_a15_l1),
                "best_a15_eff": f"{best_a15_eff:.6f}",
            }
        )

    out_table_tex.parent.mkdir(parents=True, exist_ok=True)
    with out_table_tex.open("w") as f:
        f.write("% Auto-generated by analysis/q11_energy.py\n")
        f.write("\\begin{tabular}{lrrrr}\\toprule\n")
        f.write("Application & Best L1 A7 (KB) & IPC/mW A7 & Best L1 A15 (KB) & IPC/mW A15\\\\\\midrule\n")
        for r in rows:
            f.write(
                f"{r['app']} & {r['best_a7_l1_kb']} & {r['best_a7_eff']} & {r['best_a15_l1_kb']} & {r['best_a15_eff']}\\\\\n"
            )
        f.write("\\bottomrule\\end{tabular}\n")

    print(f"Wrote figures under: {fig_base}")
    print(f"Wrote LaTeX table: {out_table_tex}")


if __name__ == "__main__":
    main()
